name: Publish Changes
on: push
jobs:
  publish-changes:
    env:
      BUCKET: iam-resource-automation-do-not-delete
      TEMPLATE: RedisCloud.yaml
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.REDISLABS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.REDISLABS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get modified files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v4.2
        
      
      - name: copy template when its changed
         if: contains(steps.changed-files.outputs.modified_files, ${{ env.TEMPLATE }})
         run: |
           aws s3 cp ${{ env.TEMPLATE }} s3://${{ BUCKET }}/
